### ISSUE TITLE
Is the offline pretraining code available?

### ISSUE THREAD

**Issue by yl1991** [ybsong00/Vital_release#6]
Dear Dr.Song,
Thank you for open-sourcing the code. The VITAL paper is an excellent work and reading the paper is an inspiring experience. 
I noted that the pretrain folder in this repo does not include the code for the offline pretraining process, as you mentioned in the Model Initialization in Section 4 of your paper. In fact, the folder is identical to that in MDNet and does not involve adversarial training. 
I was wondering if you plan to open-source the training process, which I think would be super helpful for the community to understand better how to apply GAN to the tracking problem.
Thanks for your time.
Best regards,
Yiming

**Comment by coder-LeeTao** [comment]
Hi, @yl1991 it is my understanding that VITAL use pretrain MDNet, as for adversarial training, it takes place during the frist frame and online update phase.

**Comment by yl1991** [comment]
@coder-LeeTao Hi Lee, thanks for your answer. Below is some text I found in the paper

> We initialize our model through a two-stage training. In the first step we offline pretrain the model using positive and negative samples from the training data, which is from [38]. In the second step we draw the samples from the first frame of the input sequence to finetune our model online. **During offline pretraining, we randomly initialize D and perform the training in a few iterations, then we involve G for adversarial learning.** See Sec. 3.1 for the details of the adversarial learning process where only positive samples are adopted.

I think the highlighted sentence states G is also involved in the offline training, what do you think?
